version: 2.1
description: >
  Pre-check validations

display:
  source_url: "https://github.com/TiendaNube/precheck-orb"

orbs:
  python: circleci/python@1.3.4
  orb-tools: circleci/orb-tools@10.0

# Pipeline Parameters
## These parameters are used internally by orb-tools. Skip to the Jobs section.
parameters:

  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

jobs:
  # Define one or more jobs which will utilize your orb's commands and parameters to validate your changes.
  integration-test-naming:
    executor: python/default
    steps:
      - run:
          name: "Cloning CircleCi Validation Repository"
          command: git clone --single-branch --branch "main" https://${GITHUB_TOKEN}@github.com/TiendaNube/circleci-validations.git

      - run:
          name: "Test Naming Convention"
          command: |
            export NAME_TO_VALIDATE=branch;python -m unittest discover -s circleci-validations/prechecks/python -p test_naming_validation.py

workflows:
  precheck:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint # Lint Yaml files
      - orb-tools/pack # Pack orb source
      - integration-test-naming
      # Publish development version(s) of the orb.
      - orb-tools/publish-dev:
          name: publish-dev
          orb-name: tiendanube/precheck
          alpha-version-ref: "dev:alpha"
          publish-token-variable: "CIRCLE_TOKEN"
          publish-alpha-version: true
          context: microservices # A restricted context containing your private publishing credentials. Will only execute if approved by an authorized user..
          requires:
            - orb-tools/lint # Lint Yaml files
            - orb-tools/pack # Pack orb source
            - integration-test-naming
  integration-tests_prod-release:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint # Lint Yaml files
      - orb-tools/pack # Pack orb source
      - integration-test-naming
